FROM ubuntu:noble

LABEL By="taoziG"

RUN ["apt", "update"]
RUN ["apt", "install", "-y", "ca-certificates", "tzdata", "curl", "unzip"]

# 设置默认时区为上海，可通过环境变量TZ覆盖
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 安装 qBittorrent Enhanced Edition + VueTorrent UI + Conda
WORKDIR /root
COPY ./install.sh /root/install.sh
RUN ["chmod", "+x", "/root/install.sh"]
RUN ["/bin/bash", "-c", "/root/install.sh"]
RUN ["rm", "-f", "/root/install.sh"]
ENV PATH="/root/miniconda3/bin:/root/miniconda3/condabin:$PATH"

# 设置 程序 环境变量
ENV WEBUI_PORT="8080"
ENV TORRENTING_PORT="8081"
ENV CONF_PATH="/programs"
ENV CONF_NAME=""

# 设置 程序入口
COPY ./docker-entrypoint.sh /programs/docker-entrypoint.sh
RUN ["chmod", "+x", "/programs/docker-entrypoint.sh"]
WORKDIR /programs
ENTRYPOINT [ "./docker-entrypoint.sh" ]