name: "Build Container"

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: echo "构建 Docker 镜像..."

            -
                name: "获取 Build 文件"
                uses: actions/checkout@v4
                with:
                    sparse-checkout: .
            
            -
                name: "登录 Docker Hub"
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            
            -
                name: "构建和推送 Docker 镜像"
                run:
                    cd ./docker.build
                    ./build.sh
                    docker push taozig/qbittorrent-enhanced-nox:latest